# Generated by Django 3.2.16 on 2022-12-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Item',
        ),
    ]
