# Generated by Django 4.1.4 on 2022-12-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenApp', '0002_item_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Videos',
        ),
    ]
