# Generated by Django 4.1.4 on 2022-12-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenApp', '0003_rename_item_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Videoss',
        ),
    ]
