# Generated by Django 4.1.3 on 2023-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenApp', '0004_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exerciseDecription',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
