# Generated by Django 4.1.3 on 2023-01-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenApp', '0006_alter_trainingprograms_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprograms',
            name='schedule',
        ),
        migrations.AddField(
            model_name='trainingprograms',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='authenApp.schedule'),
        ),
    ]
